stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - mkdir build
    - echo "Build complete!" > build/status.txt

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - sleep 3
    - echo "Tests passed!"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - sleep 3
    - echo "Deployment complete!!!!"
